// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdILjLkyZBFM9YZrFLRapwwJ6XHd7A2ZY',
    appId: '1:1099475857899:web:65fb7dab105b8a9f96e9ae',
    messagingSenderId: '1099475857899',
    projectId: 'commerce-1c9f6',
    authDomain: 'commerce-1c9f6.firebaseapp.com',
    storageBucket: 'commerce-1c9f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAm_F1V836MoMWLD60YPL9x7Ik-EBeQLM',
    appId: '1:1099475857899:android:93e30727ef780ccd96e9ae',
    messagingSenderId: '1099475857899',
    projectId: 'commerce-1c9f6',
    storageBucket: 'commerce-1c9f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdC0ISqPdy3xnjISnNEKKgMrD6CKH2zJI',
    appId: '1:1099475857899:ios:1b984d716e4cafd496e9ae',
    messagingSenderId: '1099475857899',
    projectId: 'commerce-1c9f6',
    storageBucket: 'commerce-1c9f6.appspot.com',
    iosClientId: '1099475857899-t8pmvulgqsv1m6fou94sdtd2n8aof648.apps.googleusercontent.com',
    iosBundleId: 'com.example.comm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdC0ISqPdy3xnjISnNEKKgMrD6CKH2zJI',
    appId: '1:1099475857899:ios:1b984d716e4cafd496e9ae',
    messagingSenderId: '1099475857899',
    projectId: 'commerce-1c9f6',
    storageBucket: 'commerce-1c9f6.appspot.com',
    iosClientId: '1099475857899-t8pmvulgqsv1m6fou94sdtd2n8aof648.apps.googleusercontent.com',
    iosBundleId: 'com.example.comm',
  );
}
